site_name: Canna-Conseils
site_email: info@canna-conseils.ca
site_tel: '(514) 844-9993 #222'
site_logo: /img/canna-conseils-logo.png
site_address_1: '414 Rue McGill, Bureau 202'
site_address_2: 'Montr√©al, QC Canada H2Y 2G1'
url_facebook: 'https://www.facebook.com/Canna-Conseils-388712571630677/'
url_instagram: ''
url_twitter: ''
url_youtube: ''
